# Generated by Django 5.2.1 on 2025-05-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kistrecords', '0003_remove_bill_vat_amount_remove_bill_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='kistrecords.patient'),
        ),
    ]
